const DESTINOS_GUIA = [
    { id: 1, nombre: 'Puerto Vallarta' },
    { id: 2, nombre: 'Riviera Nayarit' },
    { id: 3, nombre: 'Cancun' },
    { id: 6, nombre: 'Acapulco' },
    { id: 7, nombre: 'Guadalajara' },
    { id: 8, nombre: 'Bacalar' },
    { id: 9, nombre: 'Acambaro' },
    { id: 10, nombre: 'Aguascalientes' },
    { id: 11, nombre: 'Ajijic' },
    { id: 12, nombre: 'Akumal' },
    { id: 13, nombre: 'Altamira' },
    { id: 14, nombre: 'Amsterdam' },
    //{ id: 15, nombre: 'Anaheim' },
    { id: 16, nombre: 'Apodaca' },
    { id: 17, nombre: 'Arandas' },
    { id: 18, nombre: 'Arenal' },
    { id: 19, nombre: 'Arlington' },
    { id: 20, nombre: 'Aspen' },
    //{ id: 21, nombre: 'Atlanta' },
    { id: 22, nombre: 'Austin' },
    { id: 23, nombre: 'Autlán De Navarro' },
    { id: 24, nombre: 'Bahia De Banderas' },
    { id: 25, nombre: 'Baja California Norte' },
    { id: 26, nombre: 'Barcelona' },
    { id: 27, nombre: 'Barra De Navidad' },
    { id: 28, nombre: 'Belgica' },
    { id: 29, nombre: 'Belize' },
    { id: 30, nombre: 'Boca Del Rio' },
    { id: 31, nombre: 'Boca Raton' },
    { id: 32, nombre: 'Bogota' },
    { id: 33, nombre: 'Boston' },
    { id: 34, nombre: 'Bucerias' },
    { id: 35, nombre: 'Budapest' },
    { id: 36, nombre: 'Buenos Aires' },
    { id: 37, nombre: 'Cabo San Lucas' },
    { id: 38, nombre: 'Calexico' },
    { id: 39, nombre: 'Campeche' },
    { id: 40, nombre: 'Canada' },
    { id: 41, nombre: 'Cananea' },
    { id: 43, nombre: 'Caracas' },
    { id: 44, nombre: 'Cartagena' },
    { id: 45, nombre: 'Celaya' },
    { id: 46, nombre: 'Chapala' },
    { id: 47, nombre: 'Chetumal' },
    { id: 48, nombre: 'Chiapas' },
    { id: 49, nombre: 'Chicago' },
    { id: 50, nombre: 'Chichen Itza' },
    { id: 51, nombre: 'Chihuahua' },
    { id: 52, nombre: 'Chilpancingo' },
    { id: 53, nombre: 'Ciudad Acuña' },
    { id: 54, nombre: 'Ciudad De Mexico' },
    { id: 55, nombre: 'Ciudad Del Carmen' },
    { id: 56, nombre: 'Ciudad Guzman' },
    { id: 57, nombre: 'Ciudad Juarez' },
    { id: 58, nombre: 'Ciudad Madero' },
    { id: 59, nombre: 'Ciudad Obregon' },
    { id: 60, nombre: 'Ciudad Valles' },
    { id: 61, nombre: 'Ciudad Victoria' },
    { id: 62, nombre: 'Coahuila' },
    { id: 63, nombre: 'Coatzacoalcos' },
    { id: 64, nombre: 'Cocoa Beach' },
    { id: 65, nombre: 'Cocoyoc' },
    { id: 66, nombre: 'Colima' },
    { id: 67, nombre: 'Concepcion De Buenos Aires' },
    { id: 68, nombre: 'Contepec' },
    { id: 69, nombre: 'Corea Del Sur' },
    { id: 70, nombre: 'Costa Mujeres' },
    { id: 71, nombre: 'Costa Rica' },
    { id: 72, nombre: 'Costalegre' },
    { id: 73, nombre: 'Cozumel' },
    { id: 74, nombre: 'Cuautitlan' },
    { id: 75, nombre: 'Cuba' },
    { id: 76, nombre: 'Cuernavaca' },
    { id: 77, nombre: 'Culiacan' },
    { id: 78, nombre: 'Cuyutlan' },
    { id: 79, nombre: 'Dallas' },
    { id: 80, nombre: 'Denver' },
    { id: 81, nombre: 'Detroit' },
    { id: 82, nombre: 'Dubai' },
    { id: 83, nombre: 'Durango' },
    { id: 84, nombre: 'Ecatepec' },
    { id: 85, nombre: 'El Paso' },
    { id: 86, nombre: 'Ensenada' },
    { id: 87, nombre: 'Estado De Mexico' },
    { id: 88, nombre: 'Florencia' },
    { id: 89, nombre: 'Fresno' },
    { id: 90, nombre: 'Gomez Palacio' },
    { id: 91, nombre: 'Guanajuato' },
    { id: 92, nombre: 'Guasave' },
    { id: 93, nombre: 'Guatemala' },
    { id: 94, nombre: 'Guayabitos' },
    { id: 95, nombre: 'Guaymas' },
    { id: 96, nombre: 'Hawaii' },
    { id: 97, nombre: 'Hermosillo' },
    { id: 98, nombre: 'Hidalgo' },
    { id: 99, nombre: 'Holbox' },
    { id: 100, nombre: 'Hong Kong' },
    { id: 101, nombre: 'Honolulu' },
    { id: 102, nombre: 'Houston' },
    { id: 103, nombre: 'Huatulco' },
    { id: 104, nombre: 'Huatusco' },
    { id: 105, nombre: 'Iguala' },
    { id: 106, nombre: 'Irapuato' },
    { id: 107, nombre: 'Isla Mujeres' },
    { id: 108, nombre: 'Islas De San Andres' },
    { id: 109, nombre: 'Ixtapa Zihuatanejo' },
    { id: 110, nombre: 'Ixtapan De La Sal' },
    { id: 111, nombre: 'Jamaica' },
    { id: 112, nombre: 'Joao Pessoa' },
    { id: 113, nombre: 'Jocotepec' },
    { id: 114, nombre: 'Kyoto' },
    { id: 115, nombre: 'La Cruz De Huanacaxtle' },
    { id: 116, nombre: 'La Paz' },
    { id: 117, nombre: 'Lagos De Moreno' },
    { id: 118, nombre: 'Lake Tahoe' },
    { id: 119, nombre: 'Laredo' },
    { id: 120, nombre: 'Las Vegas' },
    { id: 121, nombre: 'Leon' },
    { id: 122, nombre: 'Liberia' },
    { id: 123, nombre: 'Lima' },
    { id: 124, nombre: 'Londres' },
    { id: 125, nombre: 'Long Beach' },
    { id: 126, nombre: 'Loreto' },
    { id: 127, nombre: 'Los Angeles' },
    { id: 128, nombre: 'Los Cabos' },
    { id: 129, nombre: 'Los Mochis' },
    { id: 130, nombre: 'Madrid' },
    { id: 131, nombre: 'Mahahual' },
    { id: 132, nombre: 'Manzanillo' },
    { id: 133, nombre: 'Mascota' },
    { id: 134, nombre: 'Matamoros' },
    { id: 135, nombre: 'Matehuala' },
    { id: 136, nombre: 'Mazamitla' },
    { id: 137, nombre: 'Mazatlan' },
    { id: 138, nombre: 'Mcallen' },
    { id: 139, nombre: 'Medellin' },
    { id: 140, nombre: 'Melaque' },
    { id: 141, nombre: 'Merida' },
    { id: 142, nombre: 'Mexicali' },
    { id: 143, nombre: 'Miami' },
    { id: 144, nombre: 'Minatitlan' },
    { id: 145, nombre: 'Missouri' },
    { id: 146, nombre: 'Monclova' },
    { id: 147, nombre: 'Monte Morelos' },
    { id: 148, nombre: 'Monterrey' },
    { id: 149, nombre: 'Morelia' },
    { id: 150, nombre: 'Nashville' },
    { id: 151, nombre: 'Naucalpan' },
    { id: 152, nombre: 'Nayarit' },
    { id: 153, nombre: 'New Orleans' },
    { id: 154, nombre: 'New York' },
    { id: 155, nombre: 'Nogales' },
    { id: 156, nombre: 'North Bay' },
    { id: 157, nombre: 'Nuevo Laredo' },
    { id: 158, nombre: 'Oakland' },
    { id: 159, nombre: 'Oaxaca' },
    { id: 160, nombre: 'Oklahoma' },
    { id: 161, nombre: 'Omaha' },
    { id: 162, nombre: 'Ontario' },
    { id: 163, nombre: 'Orizaba' },
    { id: 164, nombre: 'Orlando' },
    { id: 165, nombre: 'Osaka' },
    { id: 166, nombre: 'Ottawa' },
    { id: 167, nombre: 'Pachuca' },
    { id: 168, nombre: 'Palenque' },
    { id: 169, nombre: 'Panama' },
    { id: 170, nombre: 'Paris' },
    { id: 171, nombre: 'Patzcuaro' },
    { id: 172, nombre: 'Peña De Bernal' },
    { id: 173, nombre: 'Philadelphia' },
    { id: 174, nombre: 'Phoenix' },
    { id: 175, nombre: 'Piedras Negras' },
    { id: 176, nombre: 'Pittsburg' },
    { id: 177, nombre: 'Playa Del Carmen' },
    { id: 178, nombre: 'Playa Mujeres' },
    { id: 179, nombre: 'Poza Rica' },
    { id: 180, nombre: 'Praga' },
    { id: 181, nombre: 'Puebla' },
    { id: 182, nombre: 'Puerto Aventuras' },
    { id: 183, nombre: 'Puerto Escondido' },
    { id: 184, nombre: 'Puerto Morelos' },
    { id: 185, nombre: 'Puerto Peñasco Sonora' },
    { id: 186, nombre: 'Punta Cana' },
    { id: 187, nombre: 'Punta De Mita' },
    { id: 188, nombre: 'Queretaro' },
    { id: 189, nombre: 'Quiroga' },
    { id: 190, nombre: 'Quito' },
    { id: 191, nombre: 'Real De Catorce' },
    { id: 192, nombre: 'Reno' },
    { id: 193, nombre: 'Republica Dominicana' },
    { id: 194, nombre: 'Reynosa' },
    { id: 195, nombre: 'Rio De Janeiro' },
    { id: 196, nombre: 'Riviera Maya' },
    { id: 197, nombre: 'Roma' },
    { id: 198, nombre: 'Sacramento' },
    { id: 199, nombre: 'Salt Lake City' },
    { id: 200, nombre: 'Saltillo' },
    { id: 201, nombre: 'San Andres Islas' },
    { id: 202, nombre: 'San Andrés Tuxtla' },
    { id: 203, nombre: 'San Antonio' },
    { id: 204, nombre: 'San Carlos Sonora' },
    { id: 205, nombre: 'San Cristobal De Las Casas' },
    { id: 206, nombre: 'San Diego' },
    { id: 207, nombre: 'San Francisco' },
    { id: 208, nombre: 'San Jose' },
    { id: 209, nombre: 'San Jose Del Cabo' },
    { id: 210, nombre: 'San Juan De Los Lagos' },
    { id: 211, nombre: 'San Juan Del Rio' },
    { id: 212, nombre: 'San Luis Potosi' },
    { id: 213, nombre: 'San Miguel De Allende' },
    { id: 214, nombre: 'San Sebastián Del Oeste' },
    { id: 215, nombre: 'Santa Maria Del Oro' },
    { id: 216, nombre: 'Sao Paulo' },
    { id: 217, nombre: 'Sayulita' },
    { id: 218, nombre: 'Scottsdale' },
    { id: 219, nombre: 'Seattle' },
    { id: 220, nombre: 'Sevilla' },
    { id: 221, nombre: 'Shanghai' },
    { id: 222, nombre: 'Silao' },
    { id: 223, nombre: 'Springfield' },
    { id: 224, nombre: 'Tabasco' },
    { id: 225, nombre: 'Tala' },
    { id: 226, nombre: 'Talpa' },
    { id: 227, nombre: 'Tamaulipas' },
    { id: 228, nombre: 'Tampico' },
    { id: 229, nombre: 'Tapachula' },
    { id: 230, nombre: 'Tapalpa' },
    { id: 231, nombre: 'Taxco De Alarcón' },
    { id: 232, nombre: 'Tehuacán' },
    { id: 233, nombre: 'Teotihuacan' },
    { id: 234, nombre: 'Tepatitlán De Morelos' },
    { id: 235, nombre: 'Tepic' },
    { id: 236, nombre: 'Tequila' },
    { id: 237, nombre: 'Tijuana' },
    { id: 238, nombre: 'Tlalnepantla' },
    { id: 239, nombre: 'Tlaquepaque' },
    { id: 240, nombre: 'Tlaxcala' },
    { id: 241, nombre: 'Tokyo' },
    { id: 242, nombre: 'Toluca' },
    { id: 243, nombre: 'Toronto' },
    { id: 244, nombre: 'Torreon' },
    { id: 245, nombre: 'Tucson' },
    { id: 246, nombre: 'Tula De Allende' },
    { id: 247, nombre: 'Tulum' },
    { id: 248, nombre: 'Tuxtla Gutierrez' },
    { id: 249, nombre: 'Uruapan' },
    { id: 250, nombre: 'Valladolid' },
    { id: 251, nombre: 'Valle De Bravo' },
    { id: 252, nombre: 'Vancouver' },
    { id: 253, nombre: 'Varadero' },
    { id: 254, nombre: 'Venecia' },
    { id: 255, nombre: 'Veracruz' },
    { id: 256, nombre: 'Vietnam' },
    { id: 257, nombre: 'Villahermosa' },
    { id: 258, nombre: 'Washington' },
    { id: 259, nombre: 'Xalapa' },
    { id: 260, nombre: 'Yucatan' },
    { id: 261, nombre: 'Zacatecas' },
    { id: 262, nombre: 'Zamora' },
    { id: 263, nombre: 'Zapopan' },
    { id: 264, nombre: 'Zihuatanejo' },
    { id: 265, nombre: 'Distrito Federal' },
    { id: 266, nombre: 'Lazaro Cardenas' },
    { id: 267, nombre: 'Playacar' },
    { id: 268, nombre: 'Rosarito' },
    { id: 269, nombre: 'Tenacatita' },
    { id: 270, nombre: 'Uxmal' },
    { id: 272, nombre: 'Zirahuen' },
    { id: 273, nombre: 'Tehuchitlan' },
    { id: 274, nombre: 'Tuxtepec' },
    { id: 275, nombre: 'Tehuamixtle' },
    { id: 276, nombre: 'Japon' },
    { id: 277, nombre: 'Turquia' },
    { id: 278, nombre: 'Israel' },
    { id: 279, nombre: 'Alemania' },
    { id: 280, nombre: 'Colombia' },
    { id: 281, nombre: 'Brasil' },
    { id: 282, nombre: 'Chile' },
    { id: 283, nombre: 'Argentina' },
    { id: 284, nombre: 'Amealco De Bonfil' },
    { id: 285, nombre: 'Tamasopo' },
    { id: 286, nombre: 'Los Ayala' },
    { id: 287, nombre: 'Guadalupe' },
    { id: 288, nombre: 'Xalisco' },
    { id: 289, nombre: 'Tecolutla' },
    { id: 290, nombre: 'Montreal' },
    { id: 291, nombre: 'Munich' },
    { id: 292, nombre: 'Berlin' },
    { id: 293, nombre: 'Frankfurt' },
    { id: 294, nombre: 'Viena' },
    { id: 295, nombre: 'Bruselas' },
    { id: 296, nombre: 'Huamantla' },
    { id: 297, nombre: 'Salina Cruz' },
    { id: 298, nombre: 'Salamanca' },
    { id: 299, nombre: 'Tepotzotlan' },
    { id: 301, nombre: 'Barrancas Del Cobre' },
    { id: 305, nombre: 'Valle De Guadalupe' },
    { id: 306, nombre: 'Tecate' },
    { id: 307, nombre: 'Xochitepec' },
    { id: 308, nombre: 'Caborca' },
    { id: 309, nombre: 'Otros Servicios' },
    { id: 310, nombre: 'Chignahuapan' },
    { id: 311, nombre: 'San Pedro Garza' },
    { id: 312, nombre: 'Delicias' },
    { id: 313, nombre: 'La Manzanilla' },
    { id: 314, nombre: 'Zurich' },
    { id: 315, nombre: 'Perú' },
    { id: 316, nombre: 'Seúl' },
    { id: 317, nombre: 'Gyeongju' },
    { id: 318, nombre: 'Hiroshima' },
    { id: 319, nombre: 'Tokio' },
    { id: 320, nombre: 'Dolores Hidalgo' },
    { id: 321, nombre: 'Charlotte' },
    { id: 322, nombre: 'Nevada' },
    { id: 323, nombre: 'California' },
    { id: 324, nombre: 'Estados Unidos' },
    { id: 325, nombre: 'Florida' },
    { id: 326, nombre: 'Bahamas' },
    { id: 327, nombre: 'Bora Bora' },
    { id: 328, nombre: 'Portugal' },
    { id: 329, nombre: 'China' },
    { id: 330, nombre: 'Maldivas' },
    { id: 331, nombre: 'Gotemburgo' },
    { id: 332, nombre: 'Islandia' },
    { id: 333, nombre: 'Santo Domingo' },
    { id: 334, nombre: 'La Habana' },
    { id: 335, nombre: 'Cusco' },
    { id: 336, nombre: 'Fargo' },
    { id: 337, nombre: 'Helsinki' },
    { id: 338, nombre: 'Pekín' },
    { id: 339, nombre: 'Oslo' },
    { id: 340, nombre: 'Manhattan' },
    { id: 341, nombre: 'Dublin' },
    { id: 342, nombre: 'Asuncion' },
    { id: 343, nombre: 'Tulancingo' },
];